---
title: "Final Project"
author: "Justin Wininger, Otis Murray, Henry Katz"
date: "2023-11-29"
output: html_document
---

```{r setup, include=FALSE}
#load necessary packages
knitr::opts_chunk$set(echo = TRUE)
library(Stat2Data)
library(tidyverse)
library(mosaic)
library(ggformula)
library(Lock5Data)
library(tinytex)
library(car)
library(leaps)
library(HH)
library(rvest)
library(dplyr)
library(readr)
library(ggplot2)
library(tidyr)
library(readxl)
library(esquisse)
```

# Introduction



# NFl Data

```{r create nfl dataframe}
#create nfl table
nflTable <- read_html(
  x = "http://pfref.com/pi/share/d7riA"
) %>%
  html_elements(css = "table") %>%
  html_table()
nflOffense <- nflTable[[1]]
```

```{r wrangle nfl dataframe}
#delete unnecessary data
nflOffense <- subset(nflOffense, select=-c(1, 6:12, 14:18, 20:28))
nflOffense <- nflOffense[-c(1, 22:23, 36:38), ]

#rename columns 
nflOffense <- nflOffense%>%rename(
  `Team`=1, `Games`=2, `Total Points`=3, `Total Yards`=4, `Total Passing Yards`=5, `Total Rushing Yards`=6)

#squish team names
nflOffense$Team <- sub(".*\\s", "", nflOffense$Team)

#rearrange column order
#nflOffense <- nflOffense[,c("Team", "Games","Points","Yards")]

#make every cell a number versus a character
nflOffense$Games <- as.numeric(nflOffense$Games)
nflOffense$`Total Points` <- as.numeric(nflOffense$`Total Points`)
nflOffense$`Total Yards` <- as.numeric(nflOffense$`Total Yards`)
nflOffense$`Total Passing Yards` <- as.numeric(nflOffense$`Total Passing Yards`)
nflOffense$`Total Rushing Yards` <- as.numeric(nflOffense$`Total Rushing Yards`)

#make per game stats
nflOffense$`Points Per Game` <- nflOffense$`Total Points` / nflOffense$Games
nflOffense$`Yards Per Game` <- nflOffense$`Total Yards` / nflOffense$Games
nflOffense$`Passing Yards Per Game` <- nflOffense$`Total Passing Yards` / nflOffense$Games
nflOffense$`Rushing Yards Per Game` <- nflOffense$`Total Rushing Yards` / nflOffense$Games

#remove unnecessary data
nflOffense <- subset(nflOffense, select=-c(2:6))

#round down to tenths place
nflOffense$`Points Per Game` <- round(nflOffense$`Points Per Game`, digits = 1)
nflOffense$`Yards Per Game` <- round(nflOffense$`Yards Per Game`, digits = 1)
nflOffense$`Passing Yards Per Game` <- round(nflOffense$`Passing Yards Per Game`, digits = 1)
nflOffense$`Rushing Yards Per Game` <- round(nflOffense$`Rushing Yards Per Game`, digits = 1)

#rearrange columns
nflOffense <- nflOffense[, c(1, 2, 4, 5, 3)]
```

```{r create and wrangle new dataframes}
#create new dataframe with just points per game
nflOffensePPG <- subset(nflOffense, select=-c(3:5))
#order the rows by PPG 
nflOffensePPG <- nflOffensePPG[order(nflOffensePPG$`Points Per Game`, decreasing = TRUE),]

#create new dataframe with just yards per game
nflOffenseYPG <- subset(nflOffense, select=-c(2:4))
#order the rows by YPG
nflOffenseYPG <- nflOffenseYPG[order(nflOffenseYPG$`Yards Per Game`, decreasing = TRUE),]

#compare the two dataframes to see if the teams with the most YPG also have the highest PPG
head(nflOffensePPG)
head(nflOffenseYPG)
```

```{r}
#esquisse::esquisser(data=nflOffense, viewer = 'browser')
```


```{r nfl visualizations}
gf_point(`Points Per Game`~`Yards Per Game`, data=nflOffense, linewidth=1)%>%gf_lm()
gf_point(`Points Per Game`~`Passing Yards Per Game`, data=nflOffense, linewidth=1)%>%gf_lm()
gf_point(`Points Per Game`~`Rushing Yards Per Game`, data=nflOffense, linewidth=1)%>%gf_lm()
```

```{r regression anaylsis}
nflTotalYardsModel <- lm(`Points Per Game`~`Yards Per Game`, data=nflOffense)
nflPassingYardsModel <- lm(`Points Per Game`~`Passing Yards Per Game`, data=nflOffense)
nflRushingYardsModel <- lm(`Points Per Game`~`Rushing Yards Per Game`, data=nflOffense)

mplot(nflTotalYardsModel, which=1)
mplot(nflTotalYardsModel, which=2)
cooksplot(nflTotalYardsModel)
summary(nflTotalYardsModel)

mplot(nflPassingYardsModel, which=1)
mplot(nflPassingYardsModel, which=2)
cooksplot(nflPassingYardsModel)
summary(nflPassingYardsModel)

mplot(nflRushingYardsModel, which=1)
mplot(nflRushingYardsModel, which=2)
cooksplot(nflRushingYardsModel)
summary(nflRushingYardsModel)
```


```{r create college dataframe}
collegeTable <- read_html(
  x = "https://www.sports-reference.com/cfb/years/2022-team-offense.html"
) %>%
  html_elements(css = "table") %>%
  html_table()
collegeOffense <- collegeTable[[1]]

collegeOffense <- subset(collegeOffense, select=-c(1, 3, 5:7, 9:10, 12:14, 16:25))

collegeOffense <- collegeOffense%>%rename(
   `Team`=1, `Points Per Game`=2, `Passing Yards Per Game`=3, `Rushing Yards Per Game`=4, `Yards Per Game`=5
 )
collegeOffense <- collegeOffense[-c(1, 22:23, 44:45, 66:67, 88:89, 110:111, 132:133),]

collegeOffense$`Points Per Game` <- as.numeric(collegeOffense$`Points Per Game`)
collegeOffense$`Passing Yards Per Game` <- as.numeric(collegeOffense$`Passing Yards Per Game`)
collegeOffense$`Rushing Yards Per Game` <- as.numeric(collegeOffense$`Rushing Yards Per Game`)
collegeOffense$`Yards Per Game` <- as.numeric(collegeOffense$`Yards Per Game`)
```

# College Data

```{r college visualization}
gf_point(Points~Yards, data=collegeOffense, linewidth=1)%>%gf_lm()
```

```{r regression analysis}
collegeModel <- lm(Points~Yards, data=collegeOffense)
mplot(collegeModel, which=1)
mplot(collegeModel, which=2)
cooksplot(collegeModel)
summary(collegeModel)
```



two data sets, one nfl teams, one college teams, does total yards affect total points scored? Is there a relationship